module.exports = {
  user: {
    createFailed: 'Tạo người dùng thất bại',
    createSuccess: 'Tạo người dùng thành công',
    notFound: 'Người dùng không tồn tại',
    fetchSuccess: 'Lấy dữ liệu người dùng thành công',

    usernameExisted: 'Tên người dùng đã tồn tại',
    emailExisted: 'Email đã tồn tại, Vui lòng thử email khác',

    updateSuccess: 'Cập nhật người dùng thành công',
    updateFailed: 'Cập nhật người dùng không thành công',

    deleteSuccess: 'Xóa người dùng thành công',
    deleteFailed: 'Xóa người dùng thất bại',

    usernameRequired: 'Vui lòng nhập tên người dùng hợp lệ (1 - 255 ký tự).',
    usernameSpecialChars: 'Vui lòng nhập tên người dùng hợp lệ.',
    emailRequired: 'Vui lòng nhập email hợp lệ.',
    emailExists: 'Email đã tồn tại, vui lòng thử email khác.',
    emailLength: 'Vui lòng nhập email hợp lệ (1 - 255 ký tự).',
    passwordRequired: 'Vui lòng nhập mật khẩu hợp lệ (1 - 255 ký tự).',
    passwordStrength:
      'Mật khẩu phải bao gồm chữ thường, in hoa, số và ký tự đặc biệt (!@#$%^&*).',
    passwordsNotMatch: 'Mật khẩu không khớp.',
    passwordRepeatLength: 'Vui lòng nhập mật khẩu hợp lệ (1-255 ký tự).',
    passwordsDoNotMatch: 'Mật khẩu không khớp',
    coverImageRequired: 'Vui lòng chọn ảnh bìa cho tài khoản.',
    coverImageFormat: 'Vui lòng chọn định dạng hợp lệ.',
    coverImageSize:
      'Ảnh tải lên có kích thước lớn hơn 5 MB, vui lòng chọn ảnh có kích thước hợp lệ.',
    coverImageUploadError: 'Tải lên ảnh bìa thất bại, vui lòng thử lại sau.',
    roleNotFound: 'Vai trò được chọn không hợp lệ.',
    statusNotFound: 'Trạng thái được chọn không hợp lệ.',
    uploadError: 'Vui lòng chọn ảnh bìa cho tài khoản.',
    formatError: 'Vui lòng chọn định dạng hợp lệ (JPG, PNG, WEBP).',
    sizeError: 'Vui lòng chọn ảnh có kích thước hợp lệ (tối đa 5MB).',
    uploadFail: 'Tải lên ảnh bìa thất bại, vui lòng thử lại sau.',
  },
  roles: {
    invalid: 'Vai trò không hợp lệ',
  },
  chapter: {
    createFailed: 'Tạo chương thất bại',
    createSuccess: 'Tạo chương thành công',
    notFound: 'Không tìm thấy chương',
    fetchSuccess: 'Lấy dữ liệu chương thành công',

    editNotFound: 'Chương truyện không tồn tại.',
    chapterNameRequired: 'Tên chương không được để trống.',
    chapterNameSpecialChars: 'Tên chương chỉ bao gồm chữ, số.',
    chapterNameLength: 'Tên chương không được vượt quá 255 ký tự.',
    contentRequired: 'Nội dung không được để trống.',
    chapterOrderRequired: 'Số chương không được để trống.',
    chapterOrderInvalid: 'Số chương phải là số nguyên dương.',
    statusRequired: 'Bạn cần chọn trạng thái cho chương.',
    statusInvalid: 'Trạng thái đã chọn không tồn tại.',
    slugRequired: 'Slug không được để trống.',
    slugLength: 'Slug không được vượt quá 255 ký tự.',
    slugInvalid: 'Slug không được chứa khoảng trắng hoặc ký tự đặc biệt.',
    storyNotFound: 'Truyện không hợp lệ',
    storyInvalid: 'Truyện không hợp lệ',
    updateSuccess: 'Cập nhật chương thành công',
    updateFailed: 'Cập nhật chương thất bại, Không tìm thấy chương truyện.',
    deleteSuccess: 'Xóa chương thành công',
    deleteFailed: 'Xóa chương thất bại',
    cancelConfirmation: 'Bạn có muốn Hủy quá trình này không?',
  },

  review: {
    createFailed: 'Tạo đánh giá thất bại',
    createSuccess: 'Tạo đánh giá thành công',
    fetchSuccess: 'Lấy đánh giá thành công',
    updateSuccess: 'Cập nhật đánh giá thành công',
    updateFailed: 'Cập nhật đánh giá thất bại',
    deleteSuccess: 'Xóa đánh giá thành công',
    deleteFailed: 'Xóa đánh giá thất bại',
    notFound: 'Không tìm thấy đánh giá',

    // Thông báo lỗi cho các trường review
    userIdRequired: 'Vui lòng cung cấp ID người dùng.',
    userIdInvalid: 'ID người dùng không hợp lệ.',
    userIdNotExist: 'ID người dùng không tồn tại.',
    userIdNoPermission:
      'Bạn không có quyền thực hiện thao tác này với ID người dùng.',
    storyNotFound: 'Không tìm thấy truyện',
    storyIdRequired: 'Vui lòng cung cấp ID truyện.',
    storyIdNotExist: 'Truyện không tồn tại.',
    storyIdInvalid: 'ID truyện không hợp lệ.',
    starRequired: 'Vui lòng cung cấp số sao.',
    starRange: 'Số sao phải từ 1 đến 10.',
    starInvalid: 'Số sao phải là số nguyên dương',
    commentLength: 'Nội dung bình luận không được vượt quá 255 ký tự.',
    reviewNotFound: 'Đánh giá không tồn tại.',
  },

  generalErrors: {
    findSuccess: 'Tìm kiếm thành công',
    notFound: 'Không tìm thấy tài nguyên',
    serverError: 'Có lỗi xảy ra',
    dataInvalid: 'Dữ liệu không hợp lệ',
    NoUpdate: 'Không có thông tin nào được cập nhật',
    invalidDataQuery: 'Dữ liệu truy vấn không hợp lệ',
  },
  author: {
    createFailed: 'Tạo tác giả thất bại',
    createSuccess: 'Tạo tác giả thành công',
    notFound: 'Không tìm thấy tác giả',
    fetchSuccess: 'Lấy dữ liệu tác giả thành công',
    error: 'Lỗi khi lấy danh sách tác giả:',
    updateSuccess: 'Cập nhật tác giả thành công',
    updateFailed: 'Cập nhật tác giả không thành công',
    noChanges: 'Không có thay đổi nào được thực hiện.',

    deleteSuccess: 'Xóa tác giả thành công',
    deleteFailed: 'Xóa tác giả thất bại',

    author_nameRequired: 'Tham số author_name không hợp lệ: phải là một chuỗi',
    descriptionRequired: 'Tham số description không hợp lệ: phải là một chuỗi',
    sortOrderRequired: 'Tham số sort không hợp lệ: phải là "ASC" hoặc "DESC".',
    limitRequired:
      'Tham số limit không hợp lệ: phải là một số nguyên dương  và không được để trống .',
    pageRequired:
      'Tham số page không hợp lệ: phải là một số nguyên dương và không được để trống . ',
  },
  story: {
    createFailed: 'Tạo câu truyện thất bại',
    createSuccess: 'Tạo câu truyện thành công',
    notFound: 'Không tìm thấy câu truyện',
    fetchSuccess: 'Lấy dữ liệu câu truyện thành công',
    error: 'Lỗi khi lấy danh sách câu truyện:',
    updateSuccess: 'Cập nhật câu truyện thành công',
    updateFailed: 'Cập nhật câu truyện không thành công',

    deleteSuccess: 'Xóa câu truyện thành công',
    deleteFailed: 'Xóa câu truyện thất bại',
    noChanges: 'Không có thay đổi nào được thực hiện.',

    story_nameRequired: 'Tham số story_name không hợp lệ: phải là một chuỗi',
    descriptionRequired: 'Tham số description không hợp lệ: phải là một chuỗi',
    sortOrderRequired: 'Tham số sort không hợp lệ: phải là "ASC" hoặc "DESC".',
    limitRequired:
      'Tham số limit không hợp lệ: phải là một số nguyên dương  và không được để trống .',
    pageRequired:
      'Tham số page không hợp lệ: phải là một số nguyên dương và không được để trống . ',
  },
  auth: {
    accountLocked: 'Tài khoản bị khóa',
    permissionDenied: 'Quyền không hợp lệ',
    fetchProfileSuccess: 'Lấy thông tin người dùng thành công',
    createSusses: 'Đăng ký thành công',
    nameError: 'Tên đăng nhập không hợp lệ',
    nameInvalid: 'Tên đăng nhập không tồn tại',
    passwordIncorrect: 'Mật khẩu không đúng',
    registrationfailed: 'Đăng ký thất bại, vui lòng thử lại.',
    passwordNotMatch: 'Mật khẩu không khớp.',
    emailExists: 'Email đã tồn tại',
    nameExists: 'Tên đăng nhập đã tồn tại',
    emailRequired: 'Vui lòng nhập email',
    emailNotFound: 'Email không tồn tại',
    passwordRequired: 'Vui lòng nhập mật khẩu',
    unauthorized: 'Email hoặc mật khẩu không đúng',
    invalidToken: 'Token không hợp lệ',
    expiredToken: 'Token đã hết hạn',
    missedToken: 'Yêu cầu token',
    currentPasswordRequired: 'Vui lòng nhập mật khẩu hiện tại',
    avatarRequired: 'Vui lòng chọn hình ảnh',

    // Các thông báo mới được thêm vào
    passwordTooShort: 'Mật khẩu phải có ít nhất 8 ký tự.',
    passwordStrength:
      'Mật khẩu phải chứa ít nhất một chữ hoa, một chữ thường và một số.',
    passwordsDoNotMatch: 'Mật khẩu xác nhận không khớp với mật khẩu mới.',
    newPasswordRequired: 'Vui lòng nhập mật khẩu mới.',
    confirmPasswordRequired: 'Vui lòng nhập xác nhận mật khẩu mới.',
    passwordCannotBeSame:
      'Mật khẩu hiện tại và mật khẩu mới không được giống nhau.',
  },
  authreview: {
    alreadyReviewed: 'Bạn đã đánh giá truyện này',
    notFound: 'Không tìm thấy đánh giá',
    createSuccess: 'Tạo đánh giá thành công',
    updateSuccess: 'Chỉnh sửa đánh giá thành công',
    deleteSuccess: 'Xóa đánh giá thành công',
    getSuccess: 'Lấy đánh giá thành công',
  },
}
